# INFO 8065 Final Project

## Group 2 - 
### Team Name: Analytic Strategists
### Members: 
#### 1.Abin Benny
#### 2.Akshay Kochuparambil Joseph
#### 3.Arun Joy
#### 4.Sabarinath Sheela Jayamohan
#### 5.Shalu Jose
#### 6.Vidhiben Patel Nitinbhai 


In [1]:
#importing required packages
import pandas as pd
import numpy as np
import re
import os
import itertools

In [2]:
# importing data from excel file to Jupyter
data=pd.read_excel('WA_Fn-UseC_-HR-Employee-Attrition.xlsx')

### Cleaning Data if any

In [3]:
#Checking data have any null value
print(data.isnull().sum())

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

### Below lines helps to check if there is any spelling mistake, case sensitive issues or if any intger coloumn has character value etc

In [4]:
data['Age'].unique()

array([41, 49, 37, 33, 27, 32, 59, 30, 38, 36, 35, 29, 31, 34, 28, 22, 53,
       24, 21, 42, 44, 46, 39, 43, 50, 26, 48, 55, 45, 56, 23, 51, 40, 54,
       58, 20, 25, 19, 57, 52, 47, 18, 60], dtype=int64)

In [5]:
data['BusinessTravel'].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [6]:
data['DailyRate'].unique()

array([1102,  279, 1373, 1392,  591, 1005, 1324, 1358,  216, 1299,  809,
        153,  670, 1346,  103, 1389,  334, 1123, 1219,  371,  673, 1218,
        419,  391,  699, 1282, 1125,  691,  477,  705,  924, 1459,  125,
        895,  813, 1273,  869,  890,  852, 1141,  464, 1240, 1357,  994,
        721, 1360, 1065,  408, 1211, 1229,  626, 1434, 1488, 1097, 1443,
        515,  853, 1142,  655, 1115,  427,  653,  989, 1435, 1223,  836,
       1195, 1339,  664,  318, 1225, 1328, 1082,  548,  132,  746,  776,
        193,  397,  945, 1214,  111,  573, 1153, 1400,  541,  432,  288,
        669,  530,  632, 1334,  638, 1093, 1217, 1353,  120,  682,  489,
        807,  827,  871,  665, 1040, 1420,  240, 1280,  534, 1456,  658,
        142, 1127, 1031, 1189, 1354, 1467,  922,  394, 1312,  750,  441,
        684,  249,  841,  147,  528,  594,  470,  957,  542,  802, 1355,
       1150, 1329,  959, 1033, 1316,  364,  438,  689,  201, 1427,  857,
        933, 1181, 1395,  662, 1436,  194,  967, 14

In [7]:
data['Department'].unique()

array(['Sales', 'Research & Development', 'Human Resources'], dtype=object)

In [8]:
data['DistanceFromHome'].unique()

array([ 1,  8,  2,  3, 24, 23, 27, 16, 15, 26, 19, 21,  5, 11,  9,  7,  6,
       10,  4, 25, 12, 18, 29, 22, 14, 20, 28, 17, 13], dtype=int64)

In [9]:
data['Education'].unique()

array([2, 1, 4, 3, 5], dtype=int64)

In [10]:
data['EducationField'].unique()

array(['Life Sciences', 'Other', 'Medical', 'Marketing',
       'Technical Degree', 'Human Resources'], dtype=object)

In [11]:
data['EmployeeCount'].unique()

array([1], dtype=int64)

In [12]:
data['EmployeeNumber'].unique()

array([   1,    2,    4, ..., 2064, 2065, 2068], dtype=int64)

In [13]:
data['EnvironmentSatisfaction'].unique()

array([2, 3, 4, 1], dtype=int64)

In [14]:
data['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [15]:
data['HourlyRate'].unique()

array([ 94,  61,  92,  56,  40,  79,  81,  67,  44,  84,  49,  31,  93,
        50,  51,  80,  96,  78,  45,  82,  53,  83,  58,  72,  48,  42,
        41,  86,  97,  75,  33,  37,  73,  98,  36,  47,  71,  30,  43,
        99,  59,  95,  57,  76,  87,  66,  55,  32,  52,  70,  62,  64,
        63,  60, 100,  46,  39,  77,  35,  91,  54,  34,  90,  65,  88,
        85,  89,  68,  69,  74,  38], dtype=int64)

In [16]:
data['JobInvolvement'].unique()

array([3, 2, 4, 1], dtype=int64)

In [17]:
data['JobLevel'].unique()

array([2, 1, 3, 4, 5], dtype=int64)

In [18]:
data['JobRole'].unique()

array(['Sales Executive', 'Research Scientist', 'Laboratory Technician',
       'Manufacturing Director', 'Healthcare Representative', 'Manager',
       'Sales Representative', 'Research Director', 'Human Resources'],
      dtype=object)

In [19]:
data['JobSatisfaction'].unique()

array([4, 2, 3, 1], dtype=int64)

In [20]:
data['MaritalStatus'].unique()

array(['Single', 'Married', 'Divorced'], dtype=object)

In [21]:
data['MonthlyIncome'].unique()

array([5993, 5130, 2090, ..., 9991, 5390, 4404], dtype=int64)

In [22]:
data['MonthlyRate'].unique()

array([19479, 24907,  2396, ...,  5174, 13243, 10228], dtype=int64)

In [23]:
data['NumCompaniesWorked'].unique()

array([8, 1, 6, 9, 0, 4, 5, 2, 7, 3], dtype=int64)

In [24]:
data['Over18'].unique()

array(['Y'], dtype=object)

In [25]:
data['OverTime'].unique()

array(['Yes', 'No'], dtype=object)

In [26]:
data['PercentSalaryHike'].unique()

array([11, 23, 15, 12, 13, 20, 22, 21, 17, 14, 16, 18, 19, 24, 25],
      dtype=int64)

In [27]:
data['PerformanceRating'].unique()

array([3, 4], dtype=int64)

In [28]:
data['RelationshipSatisfaction'].unique()

array([1, 4, 2, 3], dtype=int64)

In [29]:
data['StandardHours'].unique()

array([80], dtype=int64)

In [30]:
data['StockOptionLevel'].unique()


array([0, 1, 3, 2], dtype=int64)

In [31]:
data['TotalWorkingYears'].unique()

array([ 8, 10,  7,  6, 12,  1, 17,  5,  3, 31, 13,  0, 26, 24, 22,  9, 19,
        2, 23, 14, 15,  4, 29, 28, 21, 25, 20, 11, 16, 37, 38, 30, 40, 18,
       36, 34, 32, 33, 35, 27], dtype=int64)

In [32]:
data['TrainingTimesLastYear'].unique()

array([0, 3, 2, 5, 1, 4, 6], dtype=int64)

In [33]:

#Any coloumn with only space is changes to none
data=data.replace(' ',None)
#Deleting any coloumn or row with no values
data=data.dropna(how='all', axis = 0)
data=data.dropna(how='all', axis = 1)
#Remove any leading or trailing white spaces from the column names
data.columns=data.columns.str.strip()

In [34]:
data

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9    

## Stage 1 analysis involves checking each column's effect on the attrition rate in a dataset.
### This analysis can help identify which columns may be the most important predictors of attrition, and can guide further analysis.

In [35]:
#Years in currentrole against attrition
count=data.loc[data['Attrition'] == 'Yes','YearsInCurrentRole'].value_counts()
count


0     73
2     68
7     31
3     16
4     15
1     11
8      7
9      6
15     2
10     2
6      2
14     1
13     1
12     1
5      1
Name: YearsInCurrentRole, dtype: int64

In [36]:
# Analysis: People with 0,2,7,3,4 years in current position tend to leave, not significant

In [37]:
#Total years(intervals considered) at company against attrition
# Define the year intervals
bins = [0, 10, 20, 30, 40]

# Label the age intervals
labels = ['0-10', '10-20', '20-30', '30-40']
data['YearInterval'] = pd.cut(data['YearsAtCompany'], bins=bins, labels=labels)

# Calculate the count of employees with attrition 'Yes' for each year interval
count = data.loc[data['Attrition'] == 'Yes'].groupby(['YearInterval']).size()

count

YearInterval
0-10     201
10-20     12
20-30      4
30-40      4
dtype: int64

In [38]:
#  Analysis:people with 0 - 10 years experience in the company tends to leave, mainly people with less experience leave

In [39]:
#WorkLifeBalance
#1 'Bad'
#2 'Good'
#3 'Better'
#4 'Best'
count=data.loc[data['Attrition'] == 'Yes','WorkLifeBalance'].value_counts()
count

3    127
2     58
4     27
1     25
Name: WorkLifeBalance, dtype: int64

In [40]:
# Analysis:People with moderat worklife balance tend to move ,which means this is not the factor that effect the attrition, not significant

In [41]:
#Attrition against the training hours for last year
#TrainingTimesLastYear gives count of no of times they got trained
count=data.loc[data['Attrition'] == 'Yes','TrainingTimesLastYear'].value_counts()
count

2    98
3    69
4    26
0    15
5    14
1     9
6     6
Name: TrainingTimesLastYear, dtype: int64

In [42]:
# Analysis:people who left comes from the moderate traing group, not significant

In [43]:
#Attrition against total years of working against age interval
# Define the year intervals
bins = [0, 10, 20, 30, 40]

# Label the age intervals
labels = ['0-10', '10-20', '20-30', '30-40']

# Create a new column for year intervals
data['YearInterval'] = pd.cut(data['TotalWorkingYears'], bins=bins, labels=labels)

# Calculate the count of employees with attrition 'Yes' for each year interval
count = data.loc[data['Attrition'] == 'Yes'].groupby(['YearInterval']).size()
count



YearInterval
0-10     177
10-20     39
20-30     11
30-40      5
dtype: int64

In [44]:
# Analysis: People with less than 10 years of total experience tends to leave the company, so choosing people with higher experience tha 10 years may help in reducing attrition. 

In [45]:
#Attrition against YearsSinceLastPromotion
count=data.loc[data['Attrition'] == 'Yes','YearsSinceLastPromotion'].value_counts()
count

0     110
1      49
2      27
7      16
3       9
6       6
4       5
9       4
15      3
13      2
11      2
5       2
10      1
14      1
Name: YearsSinceLastPromotion, dtype: int64

In [46]:
#Analysis:Those who were promoted in the recent years are leaving more,
#Reasons can be
#1.They may believ that they are incapable of this position /  they are incapabe
#2. they got promotion but is not satisfied with some other criteria and have changed 


In [47]:
# Attrition against number of years with current Manager
count=data.loc[data['Attrition'] == 'Yes','YearsWithCurrManager'].value_counts()
count

0     85
2     50
7     31
3     19
1     11
4     11
8     10
9      6
5      4
6      4
10     3
14     2
11     1
Name: YearsWithCurrManager, dtype: int64

In [48]:
# Analysis: Employees under same manager for long time( more than 8 years) do not tends to leave.
#Employees who have been working with the current managers for a short period of time tends to leave

In [49]:
#Attrition against age interval
# Define the age intervals
bins = [0, 20, 30, 40, 50]

# Label the age intervals
labels = ['below 20', '20-30', '30-40', 'above 40']

# Create a new column for age intervals
data['AgeInterval'] = pd.cut(data['Age'], bins=bins, labels=labels)

# Calculate the count of employees with attrition 'Yes' for each age interval
count = data.loc[data['Attrition'] == 'Yes'].groupby(['AgeInterval']).size()
count


AgeInterval
below 20    16
20-30       84
30-40       85
above 40    34
dtype: int64

In [50]:
# Analysis: Employee in the age interval 20-40 tends to leave the firm, 
#creating some factors to attract the people in this age group may support in reducing the attrition

In [51]:
#Attrition against business traveling type
count=data.loc[data['Attrition'] == 'Yes','BusinessTravel'].value_counts()
count

Travel_Rarely        156
Travel_Frequently     69
Non-Travel            12
Name: BusinessTravel, dtype: int64

In [52]:
#Analysis: Employee who rarely do bussiness travel tends to leave, which may not be significant

In [53]:
#Attrition against DailyRate interval
# Define the DailyRate intervals
bins = [100, 300, 500, 700, 900,1100,1300,1500]

# Label the DailyRate intervals
labels = ['100-300', '300-500', '500-700', '700-900', '900-1100', '1100-1300', '1300-1500']

# Create a new column for DailyRate intervals
data['DailyrateInterval'] = pd.cut(data['DailyRate'], bins=bins, labels=labels)

# Calculate the count of employees with attrition 'Yes' for each DailyRate interval
count = data.loc[data['Attrition'] == 'Yes'].groupby(['DailyrateInterval']).size()
count

DailyrateInterval
100-300      34
300-500      44
500-700      41
700-900      32
900-1100     30
1100-1300    23
1300-1500    33
dtype: int64

In [54]:
#Cannot find any significant insight

In [55]:
#Attrition against distance from home # Define the DailyRate intervals
bins = [0, 10, 20,30]
labels = ['0-10', '10-20', '20-30']
data['DistanceFromHomeInterval'] = pd.cut(data['DistanceFromHome'], bins=bins, labels=labels)
count = data.loc[data['Attrition'] == 'Yes'].groupby(['DistanceFromHomeInterval']).size()
count



DistanceFromHomeInterval
0-10     144
10-20     48
20-30     45
dtype: int64

In [56]:
# Employee with less distance tends to leave more

In [57]:
#Attrition against Education level
count=data.loc[data['Attrition'] == 'Yes','Education'].value_counts()
count
#Education
#1 'Below College'
#2 'College'
#3 'Bachelor'
#4 'Master'
#5 'Doctor'

3    99
4    58
2    44
1    31
5     5
Name: Education, dtype: int64

In [58]:
# Analysis Bachelors tends to leave more 
#We need to do some provision to retain Bachelors degree employees

In [59]:
#Attrition against EducationField level
count=data.loc[data['Attrition'] == 'Yes','EducationField'].value_counts()
count

Life Sciences       89
Medical             63
Marketing           35
Technical Degree    32
Other               11
Human Resources      7
Name: EducationField, dtype: int64

In [60]:
# Analysis  different fields tends to leave, which may not be significant

In [61]:
#Attrition against environment satisfaction
count=data.loc[data['Attrition'] == 'Yes','EnvironmentSatisfaction'].value_counts()
#1 'Low'
#2 'Medium'
#3 'High'
#4 'Very High'
count

1    72
3    62
4    60
2    43
Name: EnvironmentSatisfaction, dtype: int64

In [62]:
# Analysis No significant insight from ths data

In [63]:
#Attrition against gender
count=data.loc[data['Attrition'] == 'Yes','Gender'].value_counts()
count


Male      150
Female     87
Name: Gender, dtype: int64

In [64]:
# Analysis  Male tends to leave more

In [65]:
#Attrition against rate for hour rate Interval
bins = [30, 65, 100]
labels = ['30-65', '65-100']
data['HourlyRateInterval'] = pd.cut(data['HourlyRate'], bins=bins, labels=labels)
count = data.loc[data['Attrition'] == 'Yes'].groupby(['HourlyRateInterval']).size()
count

HourlyRateInterval
30-65     118
65-100    119
dtype: int64

In [66]:
#Analysis:No significant insight from this data

In [67]:
#Attrition against Job Involvement
count=data.loc[data['Attrition'] == 'Yes','JobInvolvement'].value_counts()
count
#1 'Low'
#2 'Medium'
#3 'High'
#4 'Very High'

3    125
2     71
1     28
4     13
Name: JobInvolvement, dtype: int64

In [68]:
# Analysis:  employees with moderate leve of involvement tends to leave which may not be a sihnificant attribute

In [69]:
#Attrition against job level
count=data.loc[data['Attrition'] == 'Yes','JobLevel'].value_counts()
count

1    143
2     52
3     32
5      5
4      5
Name: JobLevel, dtype: int64

In [70]:
# Analysis: employees in low job levels have higher attrition


In [71]:
#Attrition against job role
count=data.loc[data['Attrition'] == 'No','JobRole'].value_counts()
count

Sales Executive              269
Research Scientist           245
Laboratory Technician        197
Manufacturing Director       135
Healthcare Representative    122
Manager                       97
Research Director             78
Sales Representative          50
Human Resources               40
Name: JobRole, dtype: int64

In [72]:
# Analysis : Not significant

In [73]:
#Attrition against job role
count=data.loc[data['Attrition'] == 'Yes','JobRole'].value_counts()
count

Laboratory Technician        62
Sales Executive              57
Research Scientist           47
Sales Representative         33
Human Resources              12
Manufacturing Director       10
Healthcare Representative     9
Manager                       5
Research Director             2
Name: JobRole, dtype: int64

#### No significant insight from this data, may provide insight when combining with other attributes

In [74]:
#Attrition against JobSatisfaction
count=data.loc[data['Attrition'] == 'Yes','JobSatisfaction'].value_counts()
count
#1 'Low'
#2 'Medium'
#3 'High'
#4 'Very High'

3    73
1    66
4    52
2    46
Name: JobSatisfaction, dtype: int64

In [75]:
# Analysis: No significant insight from ths data

In [76]:
count=data.loc[data['Attrition'] == 'Yes','MaritalStatus'].value_counts()
count


#counting total number for each maritalstatus

Single      120
Married      84
Divorced     33
Name: MaritalStatus, dtype: int64

In [77]:
# Analysis : No significant insight from ths data

In [78]:
#attriion against monthly income range
bins = [0, 5000, 10000,15000,20000]
labels = ['0-5000', '5000-10000','10000-15000', '15000-20000']
data['MonthlyIncomeRange'] = pd.cut(data['MonthlyIncome'], bins=bins, labels=labels)
count = data.loc[data['Attrition'] == 'Yes'].groupby(['MonthlyIncomeRange']).size()
count

MonthlyIncomeRange
0-5000         163
5000-10000      49
10000-15000     20
15000-20000      5
dtype: int64

In [81]:
# Analysis: People with low wages are leaving more
#depending on performance we can consider to rovide incentives and bonus to reduce attrition

In [82]:
#attrition against employee's monthly rate range of pay
bins = [2000, 7000, 12000,17000,22000,27000]
labels = ['2000-7000', '7000-12000','12000-17000', '17000-22000','22000-27000']
data['MonthlyRateRange'] = pd.cut(data['MonthlyRate'], bins=bins, labels=labels)
count = data.loc[data['Attrition'] == 'Yes'].groupby(['MonthlyRateRange']).size()
count

MonthlyRateRange
2000-7000      46
7000-12000     53
12000-17000    42
17000-22000    48
22000-27000    48
dtype: int64

In [83]:
# Analysis : No significant insight from ths data

In [84]:
#attrition against number of companies they worked
count=data.loc[data['Attrition'] == 'Yes','NumCompaniesWorked'].value_counts()
count

1    98
0    23
7    17
4    17
6    16
5    16
2    16
3    16
9    12
8     6
Name: NumCompaniesWorked, dtype: int64

In [85]:
#Analysis:  People who have worked only in 1 company before have high attrition

In [86]:
#Attrition against overtime
count=data.loc[data['Attrition'] == 'Yes','OverTime'].value_counts()
count

Yes    127
No     110
Name: OverTime, dtype: int64

In [87]:
#Analysis:No significant insight from ths data

In [88]:
#Attrition  against salary hike percentage
count=data.loc[data['Attrition'] == 'Yes','PercentSalaryHike'].value_counts()
bins = [0, 5, 10,15,20,25]
labels = ['0-5', '5-10','10-15', '15-20','20-25']
data['PercentSalaryHikeRange'] = pd.cut(data['PercentSalaryHike'], bins=bins, labels=labels)
count = data.loc[data['Attrition'] == 'Yes'].groupby(['PercentSalaryHikeRange']).size()
count


PercentSalaryHikeRange
0-5        0
5-10       0
10-15    150
15-20     57
20-25     30
dtype: int64

In [89]:
#Analysis:Not Significant

#### 

In [90]:
#Attrition  against rate of performance
count=data.loc[data['Attrition'] == 'Yes','PerformanceRating'].value_counts()
count


3    200
4     37
Name: PerformanceRating, dtype: int64

In [91]:
#Analysis:People with moderate performance rate tend to leave company, not significant

In [92]:
#Attrition  against relationship satisfaction
count=data.loc[data['Attrition'] == 'Yes','RelationshipSatisfaction'].value_counts()
count
#1 'Low'
#2 'Medium'
#3 'High'
#4 'Very High'


3    71
4    64
1    57
2    45
Name: RelationshipSatisfaction, dtype: int64

In [93]:
#Analysis: No significant insight from ths data

In [94]:
#Attrition  against StockOptionLevel (right to purchase company stock at a specific price)
count=data.loc[data['Attrition'] == 'Yes','StockOptionLevel'].value_counts()
count

0    154
1     56
3     15
2     12
Name: StockOptionLevel, dtype: int64

In [95]:
#Analysis: Employee with less level of stock option tends to leave. 

In [96]:
#Attrition  against Department
count=data.loc[data['Attrition'] == 'Yes','Department'].value_counts()
count

Research & Development    133
Sales                      92
Human Resources            12
Name: Department, dtype: int64

## As part of first stage of Analysis we have eliminated many attributes that are not significantly effecting the attrition.

## Second Level Analysis Comparing with 2 variables, Using itertool module we have done comparison of two variable in loop

In [97]:
# all factors which need to be seggregated as intervals is done in below lines

bins1 = [20, 30, 40]
labels1 = ['20-30', '30-40']
data['AgeInterval1'] = pd.cut(data['Age'], bins=bins1, labels=labels1)

bins2 = [0, 10]
labels2 = ['0-10']
data['DistanceFromHomeInterval1'] = pd.cut(data['DistanceFromHome'], bins=bins2, labels=labels2)

bins3 = [0, 10]
labels3 = ['0-10']
data['TotalWorkingYears1'] = pd.cut(data['TotalWorkingYears'], bins=bins3, labels=labels3)
data['YearsAtCompany1'] = pd.cut(data['YearsAtCompany'], bins=bins3, labels=labels3)

bins4 = [0, 5000,10000]
labels4 = ['0-5000','5001-10000']
data['MonthlyIncomeRange1'] = pd.cut(data['MonthlyIncome'], bins=bins4, labels=labels4)

bins5=[0,8]
labels5 = ['0-8']
data['YearsWithCurrManager1'] = pd.cut(data['YearsWithCurrManager'], bins=bins5, labels=labels5)

bins6=[3,4]
labels5 = ['3-4']
data['PerformanceRating1'] = pd.cut(data['PerformanceRating'], bins=bins5, labels=labels5)

# Define the list of variables to consider
variables = ['AgeInterval1', 'Department', 'DistanceFromHomeInterval1', 'Education', 'JobLevel', 'MonthlyIncomeRange1', 'NumCompaniesWorked', 'PerformanceRating1', 'StockOptionLevel', 'TotalWorkingYears1', 'YearsAtCompany1', 'YearsSinceLastPromotion', 'YearsWithCurrManager1']

data_Education = data.loc[data['Education'] == "Bachelor's", variables]
data_JobLevel = data.loc[data['JobLevel'] == 1, variables]
data_NumCompaniesWorked1 = data.loc[data['NumCompaniesWorked'] == 1, variables]
data_StockOptionLevel0 = data.loc[data['StockOptionLevel'] == 0, variables]
data_YearsSinceLastPromotion = data.loc[data['YearsSinceLastPromotion'] == 0, variables]

# Generate all combinations of two variables
combinations = list(itertools.combinations(variables, 2))

# Loop over each combination and perform the analysis
for combination in combinations:
    # Select the two variables in the combination
    var1, var2 = combination
    
    # Count the number of employees who left the company for the combination of the two variables
    count = data.loc[data['Attrition'] == 'Yes', [var1, var2]].value_counts()
    
    # Do whatever analysis you need to do with the count
    # For example, you can print the count for each combination
    print(f"Count for {var1} and {var2}:\n{count}\n")


Count for AgeInterval1 and Department:
AgeInterval1  Department            
20-30         Research & Development    51
30-40         Research & Development    47
              Sales                     34
20-30         Sales                     27
              Human Resources            6
30-40         Human Resources            4
dtype: int64

Count for AgeInterval1 and DistanceFromHomeInterval1:
AgeInterval1  DistanceFromHomeInterval1
20-30         0-10                         51
30-40         0-10                         47
dtype: int64

Count for AgeInterval1 and Education:
AgeInterval1  Education
20-30         3            37
30-40         3            34
              4            29
20-30         1            18
              2            14
              4            14
30-40         2            13
              1             6
              5             3
20-30         5             1
dtype: int64

Count for AgeInterval1 and JobLevel:
AgeInterval1  JobLevel
20-30         1 

Count for Education and TotalWorkingYears1:
Education  TotalWorkingYears1
3          0-10                  79
4          0-10                  39
2          0-10                  33
1          0-10                  23
5          0-10                   3
dtype: int64

Count for Education and YearsAtCompany1:
Education  YearsAtCompany1
3          0-10               87
4          0-10               46
2          0-10               39
1          0-10               25
5          0-10                4
dtype: int64

Count for Education and YearsSinceLastPromotion:
Education  YearsSinceLastPromotion
3          0                          55
4          0                          23
3          1                          18
2          0                          17
           1                          14
1          0                          14
3          2                          11
1          1                           9
4          2                           8
2          2                    

## Result of Second Level Analysis
### By Observing the second leve Analysis we were able to come to a conclusion that, many factors/ attributes we considered in the first step of Analysis is not truly contributing to the attrition, like years in current company, current managers etc. 
### we can clearly see highest attrition is happening is for whom the Salary is less than 10000 and the their stock option level  is low and most of them are from Research and development team and a good number from sale department. In conclusion their remuneration is low.One important fact of the employee who leave is, majority of them are with high performance rate retaining them will increase the profitability.  